---
# When sending collectd statistics data to fluentd,
# If fluentd is not running collectd will log errors messages when trying to connect to fluentd.
# If fluentd is not running we stop collectd.
- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: pause for fluentd to start
  pause:
    seconds: 5

- name: Check if fluentd is running
  command: systemctl is-active '{{ fluentd_service_name }}'
  register: service_fluentd_status
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: set fluentd_is_running fact
  set_fact:
    fluentd_is_running: >-
      {{ service_fluentd_status.rc == 0 }}

- name: Is fluentd running
  debug:
    msg="{{ fluentd_is_running }}"
